### ISSUE TITLE
FR: Add support for USB cameras

### ISSUE THREAD

**Issue by roamingthings** [mryel00/spyglass#23] opened 2023-02-05 12:02 UTC
The use-case we are targeting with spyglass my include setups where Raspberry Pi cameras are used along with general USB cameras.

It's important to note that spyglass will only allow to use one camera at a time (e.g. if there is more than one camera you have to start spyglass multiple times).

Spyglass should be able to use USB cameras to capture images and videos.

## Questions

* Why do we need to support USB cameras
* Are there any other projects that suite this use-case better than wie can/will do?
* If there are other projects does this imply performance issues on the system that we aim to support (Raspberry Pi with restricted resources)

**Comment by mryel00** [comment] 2023-02-05 15:43
One of the goals of this project is to support camera module v3 with [crowsnest](https://github.com/mainsail-crew/crowsnest).
As @KwadFan reported previously there might be some issues with USB cameras and ustreamer on Raspberry Pi if you disable the legacy camera stack.
The support of USB cameras with spyglass would solve this issue without the need of installing/building other projects or installing extra dependencies for them.
One positive thing about the direct implementation would be that USB cameras can be controlled like CSI cameras without the need of an interface for another tool.
We only grab the frames directly from the camera without encoding anything, so there won't be much performance gains from another library.

**Comment by roamingthings** [comment] 2023-02-06 18:54
Sounds good. Thanks for clarification.

**Comment by stijnb1234** [comment] 2023-08-27 17:22
Is it currently already possible to use USB camera's with Spyglass in combination with other software?

**Comment by mryel00** [comment] 2023-08-27 18:07
@stijnb1234 The problem isn't and never will be spyglass directly. The only problem would be about libcamera, but it seems like it was just a configuration error that lead to this conclusion iirc.
So there shouldn't be any problems if you use an USB camera, relying on the normal UVC driver of linux.
As #10 is already a long time on stale and I recently looked into the USB camera support of picamera2 again, I might work on it so that you can use USB cameras directly with spyglass, as this FR intends.

**Comment by mryel00** [comment] 2024-08-14 17:35
Merged with #10

**Closed by mryel00** 2024-08-14 17:35 UTC
Labels: enhancement
